<?php

namespace ProyectoScrum\Controlador;

require 'vendor/autoload.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-25 at 19:31:22.
 */
class ControladorMySQLTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ControladorMySQL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ControladorMySQL::ejecutar
     * @todo   Implement testEjecutar().
     * @dataProvider proveedorDePruebas
     */
    public function testEjecutar($prueba, $tipo) {
        $this->object = new ControladorMySQL($tipo,  "prueba", "prueba");
        return $this->assertEquals($this->object->ejecutar($prueba), $tipo);
    }

    public function proveedorDePruebas(){
        return array(
            "Inserto"=> array(true, "insert"),
            "Select"=> array(true, "select"),
            "Update"=> array(true, "update"),
            "Delete"=> array(true, "delete")
        );
    }
    
}
